services:
  quot:
    image: kou029w/quot
    build: "."
    restart: unless-stopped
    ports: ["8080:8080"]
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@/postgres?host=/var/run/postgresql
    volumes:
      - postgres_socket:/var/run/postgresql
    depends_on: [db]
  dbmate:
    profiles: [dev]
    image: amacneil/dbmate:1.15
    command: --wait up
    user: ${UID:-1000}:${GID:-1000}
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@/postgres?host=/var/run/postgresql
    volumes:
      - ./db:/db
      - postgres_socket:/var/run/postgresql
    depends_on: [db]
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_socket:/var/run/postgresql
      - postgres_data_v14:/var/lib/postgresql/data
volumes:
  postgres_socket:
  postgres_data_v14:
