// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#rOQOPOOOOOO'#Cf'#CfOYOPO'#CfQ_OQOOOOOO,59Q,59QOOOO'#Cb'#CbOmOQO'#ChO{OSO'#CcOpOQO'#ChOOOO'#Ch'#ChOOOO'#Ca'#CaQ_OQOOOOOO-E6`-E6`O!ZOQO,59SOOOO,59S,59SOOOO'#Cd'#CdO!fOSO,58}OOOO-E6a-E6aOOOO-E6_-E6_OOOO1G.n1G.nOOOO-E6b-E6b",
  stateData: "!w~OQQOZPO~OZSO~ORTOSVOZXO]VO~ORTOSVOZ^O]VO~O^_OSVXZVX]VX~OSVOZcO]VO~O^_OSVaZVa]Va~OS]~",
  goto: "!T]PPPPP^dkvP|P!PQZRRbZSURZR[USWRZQ]UTaW]Q`VRd`RROTYRZ",
  nodeNames: "⚠ Document Heading Indent AutoLink",
  maxTerm: 14,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "(h~RWOXkXY!gYZ#PZpkpq!gq#[k#[#]#U#]~kVrTQP]UOXkXY!RZpkpq!Rq~kP!WTQPOX!RXY!RZp!Rpq!Rq~!RV!pTQPRQ^SOX!RXY!RZp!Rpq!Rq~!R~#UOZ~V#]VQP]UOXkXY!RZpkpq!Rq#hk#h#i#r#i~kV#yVQP]UOXkXY!RZpkpq!Rq#hk#h#i$`#i~kV$gVQP]UOXkXY!RZpkpq!Rq#dk#d#e$|#e~kV%TXQP]UOXkXY!RZpkpq!Rq![k![!]%p!]#gk#g#h'z#h~kV%wVQP]UOXkXY!RZpkpq!Rq!Pk!P!Q&^!Q~kV&eVQP]UOXkXY!RZpkpq!Rq!Pk!P!Q&z!Q~kV'RTQP]UOX'bXY!RZp'bpq!Rq~'bV'kTQPSU]UOX'bXY!RZp'bpq!Rq~'bV(RVQP]UOXkXY!RZpkpq!Rq![k![!]%p!]~k",
  tokenizers: [0, 1, 2],
  topRules: {"Document":[0,1]},
  tokenPrec: 82
})
